# This is a basic workflow to help you get started with Actions

name: Quiz API - Container Build

on:
#  push:
#    branches: [ main ]
#    paths: "quiz-api/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore ./quiz-api/quiz-api.csproj

      - name: Build
        run: dotnet build ./quiz-api/quiz-api.csproj --no-restore

      - name: Publish
        run: dotnet publish ./quiz-api/quiz-api.csproj -c Release -o './quiz-api/quiz-api-app' 

      - uses: azure/docker-login@v1 
        with: 
          login-server: rbrquiz.azurecr.io
          username: ${{ secrets.ACR_USERNAME }} 
          password: ${{ secrets.ACR_PASSWORD }} 

      - run: | 
          docker build ./quiz-api -t rbrquiz.azurecr.io/quiz-api:${{ github.run_number }} 
          docker push rbrquiz.azurecr.io/quiz-api:${{ github.run_number }} 
