name: "Quiz API"

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: quiz-api/**
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./quiz-api/quiz-api.csproj
    - name: Build
      run: dotnet build ./quiz-api/quiz-api.csproj --no-restore
    
